<?php
include '../core/DBmanager.php';
DBmanager::init();
set_time_limit(600);
// Автозаполнение рассписания по дням шаблонам
$startDate = '02.12.2013';
$weekCount = 15;

$lessonTT = array(
    1 => 'Complex',
    2 => 'Grammar',
    3 => 'Discussion',
    5 => 'Writting',
    7 => 'Listening'
);
    function insertOrUpdateRoomTime($roomID, $timeStart) {
        $DB_date_format = 'Y-m-d H:i:s';
        $lessonStartTime = date($DB_date_format, $timeStart);
        $lessonEndTime = date($DB_date_format, $timeStart + 3600);
        
        $qRT = sprintf('INSERT INTO `' . cnf::$db_prefix . 'roomtime`(`room`,`timestart`,`timeend`) VALUES(%d,"%s","%s") ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(`id`)',
            $roomID, $lessonStartTime, $lessonEndTime);
    
    mysql_query($qRT) or die(mysql_error() . "\n" . $qRT);
    
        return mysql_insert_id();
    }
    
    function insertNewLesson ($lesson_type, $levelID, $roomtimeID, $topic) {
        $qL = sprintf('INSERT INTO `' . cnf::$db_prefix . 'lessons`(`lesson_type`, `level`, `roomtimeID`,`teacher`,`status`,`topic`) VALUES(%d, %d, %d, %s, %d, "%s")', 
            $lesson_type, 
            $levelID, 
            $roomtimeID,
            'NULL',
            1,
            $topic
        );

        mysql_query($qL) or die(mysql_error() . $qL);
    }
// Темы
if (true) {
$topics = array(
    // Elementary
    '1' => array(
        // Complex (1)
        1 => array(
            'Сountries',
            'Your things',
            'Relatives',
            'My daily life',
            'Your things',
            'Animals can',
            'There is a bed in the bedroom',
            'Breakfast',
            'The weather',
            'There is a bed in the bedroom',
            'What is your favourite transport?',
            'What country is better',
            'Geometric shapes',
            'Daily life in Britain',
            'What country is better',
            'Will you watch TV at night?',
            'Animals have got',
            'I eat much bread',
            'When I was a child',
            'Animals have got',
            'I can buy',
            'What are you wearing',
            'What\'s the weather like?',
            'An english village',
            'What are you wearing',
            'I see the sea (senses)',
            'The royal family',
            'What time do you',
            'Making origami',
            'The royal family',
            'Foot-feet, tooth-teeth',
            'Cuisine around the world',
            'The biggest and the most expensive',
            'What does he like?',
            'Cuisine around the world',
            'Robin hood lived in the forest',
            'Animal farm',
            'A room of my dream',
            'Exotic fruit',
            'Animal farm',
            'Who invented telephone',
            'How much is it',
            'The longest bus ride',
            'More things',
            'How much is it',
            'My father is a farmer',
            'What time is it',
            'The cat family',
            'vegetable salad',
            'What time is it',
            'Soldiers wear khaki',
            'When it is spring',
            'How do you get from A to B',
            'Magic australia',
            'When it is spring',
            'Likes and hates',
            'Chocolate',
            'World markets',
            'Hobbies',
            'Chocolate',
            'What can animals do',
            'Traditional food',
            'Tim berners-lee',
            'I was in Moscow',
            'Traditional food',
            'Eating habits',
            'Million dollar idea',
            'What is there in…',
            'Romeo and Juliet',
            'Million dollar idea',
            'Describing things',
            'Gap years',
            'My free time',
            'I will dance on Sunday',
            'Gap years'
        ),
        // Grammar (2)
        2 => array(
            'Comparatives',
            'Articles',
            'Present simple: positive, negative',
            'To be present',
            'Noun plural forms',
            'Superlatives',
            'Present simple 3rd person sg (+ - ?)',
            'Conjunctions (and, but, or, so, because, as)',
            'This/ these, that/those', 
            'Cardinal & ordinal numerals',
            'Future simple',
            'To be past',
            'There is, there are',
            'Impersonal sentences',
            'Word order',
            'Have got, has got',
            'Present continuous',
            'General and alternative questions (to be present, can, will)',
            'Can positive, negative, questions',
            'Should positive, negative, questions',
            'Personal and possessive pronouns',
            'Past simple positive, regular and irregular Vs, 10 easiest irreglar Vs',
            'Many, much, a few, a little',
            'Possessive nouns sg.pl',
            'Zero conditional',
            'Personal and object pronouns',
            'Must and have to',
            'Adverbs',
            'Past simple negative and questions',
            'Question words'
        ),
        // Discussion (3)
        3 => array(
            'Favourite food',
            'Me and music',
            'Reading habits',
            'Clothes and styles',
            'Favourite holidays',
            'The best weekend',
            'Sports and Recreation',
            'Can your signiture reveal your personality?',
            'The best birthday party',
            'Meeting people is easy',
            'A house of my dream',
            'Shopping',
            'Sightseeing',
            'Letters vs emails',
            'Can your star signs reveal your personality?',
            'Why do we like winter?',
            'Describing a family',
            'Things I have with me every day',
            'Ways to keeep fit',
            'Computer games: pros and cons',
            'Ways to improve your memory',
            'What annoys you the most',
            'Movies and Moviemaking',
            'Should textbooks be replaced with netbooks?',
            'Friendship',
            'If you could have a wild animal from anywhere in the world as a pet, what animal would you choose?',
            'How to be a good listener',
            'What makes you feel better?',
            'Are computers and video games really harmful for kids?',
            'Breakfast is the most important meal of the day',
            'Unusual Hobbies',
            'Go shopping',
            'Traits of character',
            'What are the pros and cons of owning a pet?',
            'Rules I hate to obey',
            'A room of my dream',
            'Good manners',
            'The influence of weather on your mood',
            'Household chores',
            'My favourite day of the week',
            'My favourite holiday',
            'Vegetarianism - benefits and disadvantages',
            'Influence of music on your life and mood',
            'Going to the cinema',
            'Unusual houses',
            'The Giant called the Internet',
            'Genres of films',
            'Olympic Sports',
            'Travelling',
            'Unusual pets: pros and cons',
            'Fashion in our life',
            'How not to lose your temper',
            'Habits and hobbies',
            'Unusual cars',
            'Pros and cons of different kinds of transport',
            'Can colours reveal your personality?',
            'Why do we like spring?',
            'If you could be an animal, what animal would you choose to be and why?',
            'What\'s your opinion on graffiti?',
            'How will the world look in 100 years?',
            'Which temperament are you?',
            'Who or what inspires you?',
            'If you could bring one character to life from your favorite book, who would it be?',
            'Why do we like summer?',
            'Spending money',
            'Favourites',
            'If you were God for a day, what would you do?',
            'Reading books is better than watching films based on them.',
            'What scares you the most and why?',
            'What technology couldn\'t you live without?',
            'How would you spend your ideal day?',
            'What three things you regret not learning to do?',
            'What’s your favorite cuisine?',
            'What are you good at?',
            'Why do we like autumn?'
        ),
        // Listening (7)
        7 => array(
            'Royal family. Princess Diana.',
            'Risky sport.',
            'Never give up. Failures of famous people.',
            'Sightseeing. Wonders of the world.',
            'Cuisine around the world',
            'Useful devices. Do we really need so many?',
            'Weather forecast',
            'Celebrations around the world',
            'Buying a ticket (at the airport, train station) dialogues.',
            'Describing jobs.',
            'In a café, restaurant (ordering food).',
            'At the shops (buying food).',
            'Giving directions (dialogues)',
            'At the cinema (describing films)',
            'Education around the world'
        ),
        // Writting (5)
        5 => array(
            'Writing a postcard',
            'TO DO LIST',
            'Comments',
            'Write a Story with These Words',
            'Text messages',
            'Interview questions',
            'e-mail',
            'Instractions',
            'Descriptions',
            'Finish the Story',
            'News',
            'Write a Conversation',
            'Write a Story about an Object',
            'Shoping list',
            'Write a Story about This Picture'
        )
    ), 
    // Pre-intermediate
    '2' => array(
        // Complex (1)
        1 => array(
            'Describing physical appearance',
            'Summer sports',
            'Famous world festivals',
            'Professions',
            'Summer sports',
            'Good morning',
            'Packing',
            'What\'s in the city?',
            'Ways of cooking',
            'Packing',
            'The psychology of music',
            'Do goodies wear hoodies',
            'Usually and now',
            'Stuck in a rut',
            'Do goodies wear hoodies',
            'Love story',
            'Afraid of nothing',
            'When travelling abroad',
            'Unusual animals',
            'Afraid of nothing',
            'If we build',
            'Healthy food',
            'Types of shops',
            'Morris dancing',
            'Healthy food',
            'Appearance is deceitful',
            'Winter sports',
            'The British spy',
            'The pretender',
            'Winter sports',
            'I am happy when… (emotions)',
            'How many telephones have you had?',
            'Famous people and their success',
            'New Zealand',
            'How many telephones have you had?',
            'Uninhabited island',
            'Giving directions',
            'Describing food',
            'Famous brands',
            'Giving directions',
            'Body language',
            'Surf\'s up',
            'Hobbies',
            'Are you superstitious',
            'Surf\'s up',
            'My classmates',
            'My holiday',
            'Animals',
            'Plan a city',
            'My holiday',
            'How to make perfect chocolate',
            'Buying goods',
            'Music',
            'Ideals of beauty in history',
            'Buying goods',
            'Happy birthday',
            'What can you do at work',
            'Take a risk',
            'Nature around',
            'What can you do at work',
            'Drinks',
            'Freddie mercury',
            'Holiday plans',
            'Early to bed and early to rise',
            'Freddie mercury',
            'Modes of transport',
            'The worst holiday',
            'Me and music',
            'Places to do sports',
            'The worst holiday',
            'The American flag',
            'Sightseeing in the world',
            'Breakfast',
            'What do you eat',
            'Sightseeing in the world'
        ),
        // Grammar (2)
        2 => array(
            'General Questions (to be present, past, can, should, will )',
            'Used to',
            'Present Simple',
            'Adverbs (quick-quickly, fast - fast, hard-hardly.words with different meanings)',
            'Past simple positive (regular, Vs, irreg Vs, List of 15-20 irreg Vs)',
            'Relative clauses',
            'Quantifiers (many, much, a lot of, some, several)',
            'Future Simple',
            'Present simple vs present continuous',
            'Nous Countable, UnC.',
            'Going to & present continuous for personal plans',
            'Articles',
            'Quantifiers 2 (little, a little, few, a few )',
            'Prepositions of place and movement',
            'Present Continuous',
            'Comparatives & Superelatives',
            'Modal verbs must, must not',
            'Present Simple Passive',
            '1st conditional',
            'Modal verbs can, cannot',
            'Zero article',
            'Present perfect',
            'To be present and past  positive,negative, questions',
            'Phrases followed by the gerund and infinitive',
            'Present Simple positive sg &pl adverbs of frequency & word order',
            'Modal verbs should, should not',
            'Infinitives after adjectives (It is important  to do...  )',
            'Past simple negative and questions',
            'Special Questions',
            'Modal verbs have to , must'
        ),
        // Discussion (3)
        3 => array(
            'Favourite food',
            'Me and music',
            'Reading habits',
            'Clothes and styles',
            'Favourite holidays',
            'The best weekend',
            'Sports and Recreation',
            'Can your signiture and handwriting reveal your personality?',
            'The best birthday party',
            'Meeting people is easy',
            'A house of my dream',
            'Shopping',
            'Sightseeing',
            'Letters vs emails',
            'Can your star signs reveal your personality?',
            'Super power',
            'Skills you need for a job',
            'Things I have with me every day',
            'Ways to keeep fit',
            'Computer games: pros and cons',
            'Ways to improuve your memory',
            'What annoys you the most',
            'Movies and Moviemaking',
            'Should textbooks be replaced with netbooks?',
            'Friendship',
            'If you could have a wild animal from anywhere in the world as a pet, what animal would you choose?',
            'How to be a good listener',
            'What makes you feel better?',
            'Are computers and video games really harmful for kids?',
            'Breakfast is the most important meal of the day',
            'Unusual Hobbies',
            'Go shopping',
            'Traits of character',
            'What are the pros and cons of owning a pet?',
            'Rules I hate to obey',
            'A room of my dream',
            'Good manners',
            'The influence of weather on your mood',
            'Household chores',
            'My favourite day of the week',
            'My favourite holiday',
            'Vegetarianism - benefits and disadvantages',
            'Influence of music on your life and mood',
            'Going to the cinema',
            'Unusual houses',
            'The Giant called the Internet',
            'Genres of films',
            'Olympic Sports',
            'Travelling',
            'Unusual pets: pros and cons',
            'Fashion in our life',
            'How not to lose your temper',
            'Habits and hobbies',
            'Unusual cars',
            'Pros and cons of different kinds of transport',
            'Can colour reveal your personality?',
            'Why is love blind? Relationships.',
            'Bilingual education. Pros and cons.',
            'Royalty',
            'Studying in the classroom vs. skype lessons',
            'Reading - an emerging trend or a dying interest?',
            'Jobs for men and women',
            'Why do we like spring?',
            'If you had to be raised by animals in the wild, what animals would be the best parents?',
            'Spending money',
            'Favourites',
            'Do we need a global language?',
            'Reading books is better than watching films based on them.',
            'What scares you the most and why?',
            'Why do we like winter?',
            'How will the world look in 100 years?',
            'Success in life',
            'Why do we like summer?',
            'Which Is More Important: Talent or Hard Work?',
            'Why do we like autumn?'
        ),
        // Listening (7)
        7 => array(
            'Royal family. Princess Diana.',
            'Risky sport.',
            'Never give up. Failures of famous people.',
            'Sightseeing. Wonders of the world.',
            'Cuisine around the world',
            'Useful devices. Do we really need so many?',
            'Weather forecast',
            'Celebrations around the world',
            'Buying a ticket (at the airport, train station) dialogues.',
            'Describing jobs.',
            'In a café, restaurant (ordering food).',
            'At the shops (buying food).',
            'Giving directions (dialogues)',
            'At the cinema (describing films)',
            'Education around the world'
        ),
        // Writting (5)
        5 => array(
            'Invitations',
            'e-mail',
            'Essay',
            'Letter of complain',
            'Review',
            'Summary',
            'Recipes',
            'Resume',
            'Menus',
            'Article',
            'News',
            'Write a Conversation',
            'Write a Story about an Object',
            'Finish the Story',
            'Write a Story about This Picture'
        )
    ), 
    
    // Intermediate
    '3' => array(
        // Complex (1)
        1 => array(
            'Spending time',
            'Childhood memory',
            'Rivers',
            'Can we make our own luck',
            'Childhood memory',
            'Describing jobs',
            'Are you a couch potato?',
            'Agatha Christie video',
            'Is technology really helpful?',
            'Are you a couch potato?',
            'Spending money',
            'Rules at work',
            'Unusual schools',
            'Working day',
            'Rules at work',
            'Improve your memory',
            'The Namib desert',
            'Success and changes',
            'The perfect job (criteria for choosing a job )',
            'The Namib desert',
            'Computer games - pros and cons',
            'Things I\'d hate to be wihtout',
            'It is what you don\'t say that matters',
            'Unusual teaching methods',
            'Things I\'d hate to be wihtout',
            'Working day_video',
            'Me in the 1st class',
            'The crystal scull',
            'Me in future',
            'Me in the 1st class',
            'Describing impressions and situations',
            'How to be a successful inventor',
            'Working teenagers',
            'Online learning',
            'How to be a successful inventor',
            'Personality',
            'Me one year ago',
            'Places to visit',
            'Choose a candidate',
            'Me one year ago',
            'Among people (rules of behaviour)',
            'The lucky generation',
            'Lottery in st Ambrosia',
            'Crazy laws in America',
            'The lucky generation',
            'Juku',
            'Finding things in common',
            'When I met you',
            'Describing a city',
            'Finding things in common',
            'My life story',
            'Office work',
            'Movie genres',
            'Describing things',
            'Office work',
            'Rules in the past',
            'Unschooling',
            'Tips for travellers',
            'Online relationships',
            'Unschooling',
            'Future isn\'t far',
            'Under what circumstances would you…',
            'Family values',
            'Myth or reality',
            'Under what circumstances would you…',
            'Design a tour of your country',
            'Things are done in an office',
            'Parties',
            'Crazy laws in America',
            'Things are done in an office',
            'Australia',
            'Writing a resume',
            'Study techniques',
            'reversing roles',
            'Writing a resume'
        ),
        // Grammar (2)
        2 => array(
            'Reported Speech Statement',
            'So do I /Neither do I',
            '1st conditional',
            'Relative clauses',
            'Ways of expressing future',
            'Simple passive all forms',
            'Modal verbs - past forms',
            'Present perfect vs. Past simple',
            '2nd conditional',
            'Reported Speech Questions (General Q,Special Q)',
            'Past Perfect & Past Simple',
            'Articles with geographic names',
            '3rd conditional',
            'Phrases followed by the infinitive',
            'Modal verbs positive and negative',
            'some, any, no ( body, thing, where ) +, -, ?',
            'Noun-forming suffixes, adjective-forming suffixes',
            'Prepositions of time and place',
            'Used to /Be used to/get used to',
            'Present perfect and present perfect continuous',
            'Tag questions',
            'Active voice vs passive voice (on the examples of simple tense forms )',
            'Past Simple vs Past Continuous',
            'Present perfect all meanings',
            'ing, ed, adjectives',
            'Modal verbs of obligations',
            'Preposition+noun, noun+preposition',
            'Negative prefixes',
            'Phrases followed by the gerund',
            'Adjective+preposition'
        ),
        // Discussion (3)
        3 => array(
            'I am unique because…',
            'Marriage contract',
            'Reading habits',
            'Me in childhood',
            'If I were the president',
            'Corporate culture',
            'Success of famous people',
            'The perfect weekend',
            'The best birthday party',
            'Learning online',
            'Twins in a family',
            'Moral values in modern life',
            'Can we make our own luck?',
            'Skills you need for a job',
            'Superstitions and stereotypes',
            'Super power',
            'Leadership and control',
            'Beauty and Beast',
            'Gender differences',
            'Life on the edge - risky things in our life',
            'To be with Russia or to be with EU',
            'What annoys you the most',
            'Art of speech',
            'Language barriers, mixed marriages',
            'The problem of unemployment',
            'Advertising: pros and cons',
            'Domestic violence, how to fight it',
            'Job of my dream',
            'Start up',
            'Censorship',
            'Mass media',
            'Homeless people/animals',
            'Animal experimentations: pros and cons',
            'Gambling',
            'Boorishness',
            'Zoo: pros and cons',
            'Surrogate motherhood',
            'Ban human cloning',
            'For capital punishment or life inprisonment',
            'Social networks + ciber bullying',
            'Teenagers and TV',
            'Supports the legalisation of drugs',
            'Who should be the breadwinner of the family?',
            'Guns: pros and cons',
            'Big family vs the only child',
            'Should we ban smoking in public places',
            'Bribes',
            'What can reveal your personality',
            'Who is the worst chatterbox: men or women',
            'Would you believe in love marriage',
            'Computer technology and privasy',
            'How not to lose your temper',
            'If you could have a conversation with anyone in history, who would it be?',
            'Dreams- are they a link between real and imaginary worlds?',
            'Is there such a thing called “absolute truth”',
            'When is it ok to say a “white lie?”',
            'Why is love blind? Relationships.',
            'Bilingual education. Pros and cons.',
            'Royalty',
            'Would you like a computer to be your teacher?',
            'Reading - an emerging trend or a dying interest?',
            'Are sports and games as important as studies?',
            'Are children over-influenced by fashion these days?',
            'Breakfast is the most important meal of the day',
            'Studying grammar is more important than practising conversation skills',
            'The pros and cons of having a credit card.',
            'Do we need a global language?',
            'Reading books is better than watching films based on them.',
            'What scares you the most and why?',
            'Is homeschooling effective?',
            'The pros and cons of a female President.',
            'Should we let our children believe in Santa?',
            'To be or not to be a vegetarian',
            'Been good and saying truth',
            'Myths in our life'
        ),
        // Listening (7)
        7 => array(
            'Royal family. Princess Diana.',
            'Risky sport.',
            'Never give up. Failures of famous people.',
            'Sightseeing. Wonders of the world.',
            'Cuisine around the world.',
            'J.R.R. Tolkien. “The Lord of the Rings”.',
            'The Rolling Stones (+ the song)',
            'The UFO. Paranormal activities.',
            'Public speeches. Nelson Mandela, Martin Luther King.',
            'The Iron lady. Margaret Thatcher.',
            'Is Ian Fleming a real James Bond? Life facts.',
            'Sir Alexander Fleming, the person who discovered penicillin.',
            'Sir Isaac Newton.',
            'Fashion and styles. Is fashion worth paying?',
            'Education around the world'
        ),
        // Writting (5)
        5 => array(
            'Invitations',
            'e-mail',
            'Essay',
            'Letter of complain',
            'Review',
            'Summary',
            'Recipes',
            'Resume',
            'Menus',
            'Article',
            'News',
            'Write a Conversation',
            'Write a Story about an Object',
            'Finish the Story',
            'Write a Story about This Picture'
        )
    ), 
    
    // Upper-intermediate 
    '4' => array(
        // Complex (1)
        1 => array(
            'Important events in a person\'s life',
            'Feelings and emotions',
            'Fairy tales',
            'Pets',
            'Feelings and emotions',
            'Generation gap',
            'University',
            'Christmas in different countries',
            'Job interview',
            'University',
            'Claude Monet',
            'Color predicts personality',
            'A survival story',
            'Propetry boom',
            'Color predicts personality',
            'Learning languages',
            'A catchy advert',
            'Prepare for a holiday',
            'A favourite recipe',
            'A catchy advert',
            'Romantic love lasts one year',
            'Let\'s have a meeting',
            'Paul McCartney',
            'Happy and sad',
            'Let\'s have a meeting',
            'Well-known stories',
            'Cosmetic surgery',
            'It\'s high time to cut our mother\'s apron string',
            'If university ecucation is free',
            'Cosmetic surgery',
            'Origin of christmas traditions',
            'Table manners',
            'Would you like to buy a spouse',
            'Corporate culture',
            'Table manners',
            'Show must go on',
            'The literature Nobel prize',
            'Education in the developing countries',
            'Advertising',
            'The literature Nobel prize',
            'Presents',
            'History of dating',
            'Secrets of an effective meeting',
            'More feelings and emotions',
            'History of dating',
            'Dracula',
            'A supermarket trolley',
            'A proper education',
            'A 2-km long wedding dress',
            'A supermarket trolley',
            'Genetically modified food',
            'Prenuptial agreement - a romance killer?',
            'Small talk in businss',
            'If I were in your shoes',
            'Prenuptial agreement - a romance killer?',
            'Traits of character',
            'Favourite literary characters',
            'Weddings in different countries',
            'True love',
            'Favourite literary characters',
            'Chair a meeting',
            'I wish it had been better',
            'Get stressed - stay young',
            'Da Vinci Code',
            'I wish it had been better',
            'things you\'ll never learn at school',
            'Famous world holidays',
            'Getting together in the 21st century',
            'Tricky questions',
            'Famous world holidays',
            'The speckled band',
            'Homework at school and university',
            'Healthy food',
            'The place I work in',
            'Homework at school and university'
        ),
        // Grammar (2)
        2 => array(
            'I wish , If only, it\'s high time.. In present and past',
            'Mixed conditional',
            'Have/get something done',
            'Articles',
            'Continuous tenses in active',
            'Infinitives with modal verbs',
            'Complex subject',
            'Participle I (active)',
            'Indirect Questions',
            'Phrasal verbs (break, come, get, go, hang, keep)',
            'Future Perfect & Future Perfect Continuous',
            'Modal verbs with the perfect infinitive',
            'Gerund & gerundial construction',
            'Articles 2 ( hospital, the hospital, shool, the shool, church, the church )',
            'Verb+adverb+preposition',
            'Complex object',
            'Continuous tenses in passive',
            'Perfect tenses in active',
            'Past perfect continuous & present perfect continuous',
            'Future Simple, Pr.Continuous for future, Pr. Simple for future, going to',
            'Perfect tenses in passive',
            'Reported speech & sequence of tenses',
            'Indefinite, Cont, Perfect, Infinitives (active)',
            'Passive with modal verbs',
            'Phrasal verbs (make, pull, put, stand, take)',
            'Participle I (passive)',
            '0, 1st, 2nd  3d conditional',
            'Participle II',
            'Indefinite, Cont, Perfect, Infinitives (passive)',
            'Phrasal verbs (turn, work, run, look, knock)'
        ),
        // Discussion (3)
        3 => array(
            'I am unique because…',
            'Marriage contract',
            'Reading habits',
            'Me in childhood',
            'If I were the president',
            'Corporate culture',
            'Success of famous people',
            'The perfect weekend',
            'The best birthday party',
            'Learning online',
            'Twins in a family',
            'Moral values in modern life',
            'Can we make our own luck?',
            'Skills you need for a job',
            'Superstitions and stereotypes',
            'Super power',
            'Leadership and control',
            'Beauty and Beast',
            'Gender differences',
            'Life on the edge - risky things in our life',
            'To be with Russia or to be with EU',
            'What annoys you the most',
            'Art of speech',
            'Language barriers, mixed marriages',
            'The problem of unemployment',
            'Advertising: pros and cons',
            'Domestic violence, how to fight it',
            'Job of my dream',
            'Start up',
            'Censorship',
            'Mass media',
            'Homeless people/animals',
            'Animal experimentations: pros and cons',
            'Gambling',
            'Boorishness',
            'Zoo: pros and cons',
            'Surrogate motherhood',
            'Ban human cloning',
            'For capital punishment or life inprisonment',
            'Social networks + ciber bullying',
            'Teenagers and TV',
            'Supports the legalisation of drugs',
            'Who should be the breadwinner of the family?',
            'Guns: pros and cons',
            'Big family vs the only child',
            'Should we ban smoking in public places',
            'Bribes',
            'What can reveal your personality',
            'Who is the worst chatterbox: men or women',
            'Would you believe in love marriage',
            'Computer technology and privasy',
            'How not to lose your temper',
            'If you could have a conversation with anyone in history, who would it be?',
            'Dreams- are they a link between real and imaginary worlds?',
            'Is there such a thing called “absolute truth”',
            'When is it ok to say a “white lie?”',
            'Why is love blind? Relationships.',
            'Bilingual education. Pros and cons.',
            'Royalty',
            'Would you like a computer to be your teacher?',
            'Reading - an emerging trend or a dying interest?',
            'Are sports and games as important as studies?',
            'Are children over-influenced by fashion these days?',
            'Breakfast is the most important meal of the day',
            'Studying grammar is more important than practising conversation skills',
            'The pros and cons of having a credit card.',
            'Do we need a global language?',
            'Reading books is better than watching films based on them.',
            'What scares you the most and why?',
            'Is homeschooling effective?',
            'The pros and cons of a female President.',
            'Should we let our children believe in Santa?',
            'To be or not to be a vegetarian',
            'Been good and saying truth',
            'Myths in our life'
        ),
        // Listening (7)
        7 => array(
            'Royal family. Princess Diana.',
            'Risky sport.',
            'Never give up. Failures of famous people.',
            'Sightseeing. Wonders of the world.',
            'Cuisine around the world.',
            'J.R.R. Tolkien. “The Lord of the Rings”.',
            'The Rolling Stones (+ the song)',
            'The UFO. Paranormal activities.',
            'Public speeches. Nelson Mandela, Martin Luther King.',
            'The Iron lady. Margaret Thatcher.',
            'Is Ian Fleming a real James Bond? Life facts.',
            'Sir Alexander Fleming, the person who discovered penicillin.',
            'Sir Isaac Newton.',
            'Fashion and styles. Is fashion worth paying?',
            'Education around the world'
        ),
        // Writting (5)
        5 => array(
            'Invitations',
            'e-mail',
            'Essay',
            'Letter of complain',
            'Review',
            'Summary',
            'Recipes',
            'Resume',
            'Menus',
            'Article',
            'News',
            'Write a Conversation',
            'Write a Story about an Object',
            'Finish the Story',
            'Write a Story about This Picture'
        )
    )  
);
}

// Шаблоны по дням
if (true) {
$Template = array(
    'Time' => array(
        0 => array(8, 21),
        1 => array(8, 21),
        2 => array(8, 21),
        3 => array(8, 21),
        4 => array(8, 21),
        5 => array(10, 16),
        6 => array(10, 16)
    ),
    'LessonTypes' => array(
        0 => array(1, 3), // Monday
        1 => array(3, 2), // Tuesday
        2 => array(1, 5), // Wednesday
        3 => array(1, 3), // Thursday
        4 => array(3, 7), // Friday
        5 => array(1, 2), // Saturday
        6 => array(3, 1) // Sunday
    )
);
}

// Привязка к комнатам
if (true) {
    $levelToRoom = array(
        1 => 4, // Kid
        2 => 3, // Pre-intermediate
        3 => 1, // Intermediate
        4 => 2  // Upper-intermediate
    );
}

// Само действие ;)
if (true) {
    
    $dayStep = 3600 * 24; // 1 day
    $hourStep = 3600; // 1 day
    
    foreach($topics as $levelID => $levelTopics) {
        $topicInc = array(
            1 => 0,
            2 => 0,
            3 => 0,
            5 => 0,
            7 => 0
        );
        $roomID = $levelToRoom[$levelID];
        $dateTime = strtotime($startDate);
        for ($i = 0, $n = $weekCount; $i < $n; $i++) {
            for ($iday = 0; $iday < 7; $iday++, $dateTime += $dayStep) {
                $timeInterval = $Template['Time'][$iday];
                $lessonTypeInterval = $Template['LessonTypes'][$iday];
                $dayStart = $timeInterval[0];
                $dayEnd = $timeInterval[1];

                for ($hour = $dayStart; $hour <= $dayEnd; $hour++) {
                    $lessonStartTime = $dateTime + ($hour * $hourStep);
                    $lessonType = $lessonTypeInterval[($hour - $dayStart) % 2];
                    $topic = $levelTopics[$lessonType][$topicInc[$lessonType]];
                    
                    // Insert or update roomTime
                    $roomtimeID = insertOrUpdateRoomTime($roomID, $lessonStartTime);
                    
                    // Insert new lesson
                    insertNewLesson($lessonType, $levelID, $roomtimeID, $topic);
//                    echo date('H:i d.m.Y D', $lessonStartTime) . ' - ' . $lessonTT[$lessonType] . ': ' . $topic . '<br/>';
                }
                
                $topicInc[$lessonTypeInterval[0]] ++;
                $topicInc[$lessonTypeInterval[1]] ++;
            }
        }
    }
}
?>