<?php

include '../core/DBmanager.php';
DBmanager::init();
set_time_limit(600);

header('Content-type: text/plain; charset=utf-8');

if (true) {
$topics = array(
    // Elementary
    '1' => array(
        // Complex (1)
        1 => array(
            'Сountries' => 'to be present (+ -)',
            'Your things' => 'this/these, plurals',
            'Relatives' => 'possessives',
            'My daily life' => 'present simple positive and negative pl',
            'Animals can' => 'can, cannot',
            'There is a bed in the bedroom' => 'there is/there are',
            'Breakfast' => 'many, much, a few, a little',
            'The weather' => 'impersonal sentences',
            'What is your favourite transport?' => 'question words',
            'What country is better' => 'comparatives, opposites',
            'Geometric shapes' => 'a/the',
            'Daily life in Britain' => 'present simple positive and negative pl',
            'Will you watch TV at night?' => 'will',
            'Animals have got' => 'have got',
            'I eat much bread' => 'many, much, a few, a little',
            'When I was a child' => 'was, were',
            'I can buy' => 'can',
            'What are you wearing' => 'present continuous',
            'What\'s the weather like?' => 'impersonal sentences ',
            'An english village' => 'there is/are',
            'I see the sea (senses)' => 'direct word order',
            'The royal family' => 'possessives',
            'What time do you' => 'present simple questions do',
            'Making origami' => 'present continuous',
            'Foot-feet, tooth-teeth' => 'plural forms',
            'Cuisine around the world' => 'articles',
            'The biggest and the most expensive' => 'comparisons, opposites',
            'What does he like?' => 'Present simple 3rd person sg',
            'Robin hood lived in the forest' => 'past simple positive and negative',
            'Animal farm' => 'ordinal numerals',
            'A room of my dream' => 'there is/there are',
            'Exotic fruit' => 'question words',
            'Who invented telephone' => 'past simple',
            'How much is it' => 'can',
            'The longest bus ride' => 'superlatives',
            'More things' => 'this/that/these/those',
            'My father is a farmer' => 'possessives',
            'What time is it' => 'present simple (+ -)',
            'The cat family' => 'have got',
            'vegetable salad' => 'many, much, a few, a little',
            'Soldiers wear khaki' => 'must and have to',
            'When it is spring' => 'zero conditional',
            'How do you get from A to B' => 'question words',
            'Magic australia' => 'present continuous',
            'Likes and hates' => 'Present simple 3rd person sg',
            'Chocolate' => 'should, shouldn\'t',
            'World markets' => 'comparisons, opposites',
            'Hobbies' => 'present simple pl',
            'What can animals do' => 'can (+ - ?)',
            'Traditional food' => 'alternative questions',
            'Tim berners-lee' => 'past simple positive',
            'I was in Moscow' => 'was, were',
            'Eating habits' => 'plural forms',
            'Million dollar idea' => 'question words',
            'What is there in…' => 'there is/are',
            'Romeo and Juliet' => 'past simple positive and negative',
            'Describing things' => 'a/the',
            'Gap years' => 'going to',
            'My free time' => 'Present simple 3rd person sg',
            'I will dance on Sunday' => 'will'
        ),
        // Grammar (2)
        2 => array(
            'Comparatives',
            'Articles',
            'Present simple: positive, negative',
            'To be present',
            'Noun plural forms',
            'Superlatives',
            'Present simple 3rd person sg (+ - ?)',
            'Conjunctions (and, but, or, so, because, as)',
            'This/ these, that/those', 
            'Cardinal & ordinal numerals',
            'Future simple',
            'To be past',
            'There is, there are',
            'Impersonal sentences',
            'Word order',
            'Have got, has got',
            'Present continuous',
            'General and alternative questions (to be present, can, will)',
            'Can positive, negative, questions',
            'Should positive, negative, questions',
            'Personal and possessive pronouns',
            'Past simple positive, regular and irregular Vs, 10 easiest irreglar Vs',
            'Many, much, a few, a little',
            'Possessive nouns sg.pl',
            'Zero conditional',
            'Personal and object pronouns',
            'Must and have to',
            'Adverbs',
            'Past simple negative and questions',
            'Question words'
        ),
        // Discussion (3)
        3 => array(
            'Favourite food',
            'Me and music',
            'Reading habits',
            'Clothes and styles',
            'Favourite holidays',
            'The best weekend',
            'Sports and Recreation',
            'Can your signiture reveal your personality?',
            'The best birthday party',
            'Meeting people is easy',
            'A house of my dream',
            'Shopping',
            'Sightseeing',
            'Letters vs emails',
            'Can your star signs reveal your personality?',
            'Why do we like winter?',
            'Describing a family',
            'Things I have with me every day',
            'Ways to keeep fit',
            'Computer games: pros and cons',
            'Ways to improve your memory',
            'What annoys you the most',
            'Movies and Moviemaking',
            'Should textbooks be replaced with netbooks?',
            'Friendship',
            'If you could have a wild animal from anywhere in the world as a pet, what animal would you choose?',
            'How to be a good listener',
            'What makes you feel better?',
            'Are computers and video games really harmful for kids?',
            'Breakfast is the most important meal of the day',
            'Unusual Hobbies',
            'Go shopping',
            'Traits of character',
            'What are the pros and cons of owning a pet?',
            'Rules I hate to obey',
            'A room of my dream',
            'Good manners',
            'The influence of weather on your mood',
            'Household chores',
            'My favourite day of the week',
            'My favourite holiday',
            'Vegetarianism - benefits and disadvantages',
            'Influence of music on your life and mood',
            'Going to the cinema',
            'Unusual houses',
            'The Giant called the Internet',
            'Genres of films',
            'Olympic Sports',
            'Travelling',
            'Unusual pets: pros and cons',
            'Fashion in our life',
            'How not to lose your temper',
            'Habits and hobbies',
            'Unusual cars',
            'Pros and cons of different kinds of transport',
            'Can colours reveal your personality?',
            'Why do we like spring?',
            'If you could be an animal, what animal would you choose to be and why?',
            'What\'s your opinion on graffiti?',
            'How will the world look in 100 years?',
            'Which temperament are you?',
            'Who or what inspires you?',
            'If you could bring one character to life from your favorite book, who would it be?',
            'Why do we like summer?',
            'Spending money',
            'Favourites',
            'If you were God for a day, what would you do?',
            'Reading books is better than watching films based on them.',
            'What scares you the most and why?',
            'What technology couldn\'t you live without?',
            'How would you spend your ideal day?',
            'What three things you regret not learning to do?',
            'What’s your favorite cuisine?',
            'What are you good at?',
            'Why do we like autumn?'
        ),
        // Listening (7)
        7 => array(
            'Royal family. Princess Diana.',
            'Risky sport.',
            'Never give up. Failures of famous people.',
            'Sightseeing. Wonders of the world.',
            'Cuisine around the world',
            'Useful devices. Do we really need so many?',
            'Weather forecast',
            'Celebrations around the world',
            'Buying a ticket (at the airport, train station) dialogues.',
            'Describing jobs.',
            'In a café, restaurant (ordering food).',
            'At the shops (buying food).',
            'Giving directions (dialogues)',
            'At the cinema (describing films)',
            'Education around the world'
        ),
        // Writting (5)
        5 => array(
            'Writing a postcard',
            'TO DO LIST',
            'Comments',
            'Write a Story with These Words',
            'Text messages',
            'Interview questions',
            'e-mail',
            'Instractions',
            'Descriptions',
            'Finish the Story',
            'News',
            'Write a Conversation',
            'Write a Story about an Object',
            'Shoping list',
            'Write a Story about This Picture'
        )
    ), 
    // Pre-intermediate
    '2' => array(
        // Complex (1)
        1 => array(
            'Describing physical appearance' => 'have got/has got',
            'Summer sports' => 'can',
            'Famous world festivals' => 'present continuous',
            'Professions' => 'present simple - 3rd person sg',
            'Good morning' => 'have to, must, can',
            'Packing' => 'should, must',
            'What\'s in the city?' => 'quantifiers',
            'Ways of cooking' => 'phrases followed by the gerund',
            'The psychology of music' => 'comparisons',
            'Do goodies wear hoodies' => 'general questions',
            'Usually and now' => 'present simple vs. present Continuous',
            'Stuck in a rut' => 'used to',
            'Love story' => 'past simple',
            'Afraid of nothing' => 'present perfect',
            'When travelling abroad' => 'modal verbs',
            'Unusual animals' => 'have got/has got',
            'If we build' => 'real conditions in present  and future',
            'Healthy food' => 'to be present',
            'Types of shops' => 'present simple passive',
            'Morris dancing' => 'relative clauses',
            'Appearance is deceitful' => 'adverbs',
            'Winter sports' => 'can',
            'The British spy' => 'comparatives and suprlatives',
            'The pretender' => 'had to + - ?',
            'I am happy when… (emotions)' => 'present simple ',
            'How many telephones have you had?' => 'present perfect ',
            'Famous people and their success' => 'past simple negative and quesitons',
            'New Zealand' => 'comparisons',
            'Uninhabited island' => 'real conditions',
            'Giving directions' => 'should',
            'Describing food' => 'special questions',
            'Famous brands' => 'to be past',
            'Body language' => 'present continuous',
            'Surf\'s up' => 'articles',
            'Hobbies' => 'present simple sg and pl positive',
            'Are you superstitious' => '1st conditional',
            'My classmates' => 'present perfect vs past simple',
            'My holiday' => 'past simple',
            'Animals' => 'making guesses',
            'Plan a city' => 'infinitives after adjectives',
            'How to make perfect chocolate' => 'must and must not',
            'Buying goods' => 'too much/many',
            'Music' => 'present simple',
            'Ideals of beauty in history' => 'was, were',
            'Happy birthday' => 'special questions',
            'What can you do at work' => 'can, have to',
            'Take a risk' => 'past simple,vs present perfect',
            'Nature around' => 'comparisons',
            'Drinks' => 'quantifiers',
            'Freddie mercury' => 'past simple passive',
            'Holiday plans' => 'going to',
            'Early to bed and early to rise' => 'special questions',
            'Modes of transport' => 'present simple',
            'The worst holiday' => 'past simple',
            'Me and music' => 'can',
            'Places to do sports' => 'present simple passive',
            'The American flag' => 'forming questions',
            'Sightseeing in the world' => 'present prperfect (I have visited)',
            'Breakfast' => 'present simple',
            'What do you eat' => 'quantifiers'
        ),
        // Grammar (2)
        2 => array(
            'General Questions (to be present, past, can, should, will )',
            'Used to',
            'Present Simple',
            'Adverbs (quick-quickly, fast - fast, hard-hardly.words with different meanings)',
            'Past simple positive (regular, Vs, irreg Vs, List of 15-20 irreg Vs)',
            'Relative clauses',
            'Quantifiers (many, much, a lot of, some, several)',
            'Future Simple',
            'Present simple vs present continuous',
            'Nous Countable, UnC.',
            'Going to & present continuous for personal plans',
            'Articles',
            'Quantifiers 2 (little, a little, few, a few )',
            'Prepositions of place and movement',
            'Present Continuous',
            'Comparatives & Superelatives',
            'Modal verbs must, must not',
            'Present Simple Passive',
            '1st conditional',
            'Modal verbs can, cannot',
            'Zero article',
            'Present perfect',
            'To be present and past  positive,negative, questions',
            'Phrases followed by the gerund and infinitive',
            'Present Simple positive sg &pl adverbs of frequency & word order',
            'Modal verbs should, should not',
            'Infinitives after adjectives (It is important  to do...  )',
            'Past simple negative and questions',
            'Special Questions',
            'Modal verbs have to , must'
        ),
        // Discussion (3)
        3 => array(
            'Favourite food',
            'Me and music',
            'Reading habits',
            'Clothes and styles',
            'Favourite holidays',
            'The best weekend',
            'Sports and Recreation',
            'Can your signiture and handwriting reveal your personality?',
            'The best birthday party',
            'Meeting people is easy',
            'A house of my dream',
            'Shopping',
            'Sightseeing',
            'Letters vs emails',
            'Can your star signs reveal your personality?',
            'Super power',
            'Skills you need for a job',
            'Things I have with me every day',
            'Ways to keeep fit',
            'Computer games: pros and cons',
            'Ways to improuve your memory',
            'What annoys you the most',
            'Movies and Moviemaking',
            'Should textbooks be replaced with netbooks?',
            'Friendship',
            'If you could have a wild animal from anywhere in the world as a pet, what animal would you choose?',
            'How to be a good listener',
            'What makes you feel better?',
            'Are computers and video games really harmful for kids?',
            'Breakfast is the most important meal of the day',
            'Unusual Hobbies',
            'Go shopping',
            'Traits of character',
            'What are the pros and cons of owning a pet?',
            'Rules I hate to obey',
            'A room of my dream',
            'Good manners',
            'The influence of weather on your mood',
            'Household chores',
            'My favourite day of the week',
            'My favourite holiday',
            'Vegetarianism - benefits and disadvantages',
            'Influence of music on your life and mood',
            'Going to the cinema',
            'Unusual houses',
            'The Giant called the Internet',
            'Genres of films',
            'Olympic Sports',
            'Travelling',
            'Unusual pets: pros and cons',
            'Fashion in our life',
            'How not to lose your temper',
            'Habits and hobbies',
            'Unusual cars',
            'Pros and cons of different kinds of transport',
            'Can colour reveal your personality?',
            'Why is love blind? Relationships.',
            'Bilingual education. Pros and cons.',
            'Royalty',
            'Studying in the classroom vs. skype lessons',
            'Reading - an emerging trend or a dying interest?',
            'Jobs for men and women',
            'Why do we like spring?',
            'If you had to be raised by animals in the wild, what animals would be the best parents?',
            'Spending money',
            'Favourites',
            'Do we need a global language?',
            'Reading books is better than watching films based on them.',
            'What scares you the most and why?',
            'Why do we like winter?',
            'How will the world look in 100 years?',
            'Success in life',
            'Why do we like summer?',
            'Which Is More Important: Talent or Hard Work?',
            'Why do we like autumn?'
        ),
        // Listening (7)
        7 => array(
            'Royal family. Princess Diana.',
            'Risky sport.',
            'Never give up. Failures of famous people.',
            'Sightseeing. Wonders of the world.',
            'Cuisine around the world',
            'Useful devices. Do we really need so many?',
            'Weather forecast',
            'Celebrations around the world',
            'Buying a ticket (at the airport, train station) dialogues.',
            'Describing jobs.',
            'In a café, restaurant (ordering food).',
            'At the shops (buying food).',
            'Giving directions (dialogues)',
            'At the cinema (describing films)',
            'Education around the world'
        ),
        // Writting (5)
        5 => array(
            'Invitations',
            'e-mail',
            'Essay',
            'Letter of complain',
            'Review',
            'Summary',
            'Recipes',
            'Resume',
            'Menus',
            'Article',
            'News',
            'Write a Conversation',
            'Write a Story about an Object',
            'Finish the Story',
            'Write a Story about This Picture'
        )
    ), 
    
    // Intermediate
    '3' => array(
        // Complex (1)
        1 => array(
            'Spending time' => 'present simple, adverbs of frequency',
            'Childhood memory' => 'used to/ be used to',
            'Rivers' => 'articles with geographic names',
            'Can we make our own luck' => 'word-building suffixes and prefixes',
            'Describing jobs' => 'ing, ed adjectives',
            'Are you a couch potato?' => 'gerunds',
            'Agatha Christie video' => 'tag questions',
            'Is technology really helpful?' => 'I want X to do',
            'Spending money' => 'some, any, no',
            'Rules at work' => 'modal verbs',
            'Unusual schools' => 'types of questions',
            'Working day' => 'present simple positive and negative',
            'Improve your memory' => 'prefer and would rather',
            'The Namib desert' => 'sentences starting with there and it',
            'Success and changes' => 'present perfect',
            'The perfect job (criteria for choosing a job )' => '1st conditional',
            'Computer games - pros and cons' => 'revalive clauses',
            'Things I\'d hate to be wihtout' => 'need to do vs. need doing ',
            'It is what you don\'t say that matters' => 'tag questions',
            'Unusual teaching methods' => 'present perfect vs present perfect continuous',
            'Working day_video' => 'present simple 3rd person sg',
            'Me in the 1st class' => 'used to/ be used to',
            'The crystal scull' => 'past continuous and past simple',
            'Me in future' => 'ways of expressing future',
            'Describing impressions and situations' => 'ing, ed adjectives',
            'How to be a successful inventor' => 'past simple passive',
            'Working teenagers' => 'modal verbs of obligation',
            'Online learning' => 'collcations',
            'Personality' => 'negative prefixes',
            'Me one year ago' => 'past perfect',
            'Places to visit' => 'special questions',
            'Choose a candidate' => '',
            'Among people (rules of behaviour)' => 'should',
            'The lucky generation' => 'probability',
            'Lottery in st Ambrosia' => 'real conditions in present and future',
            'Crazy laws in America' => 'modal verbs',
            'Juku' => 'asking questions',
            'Finding things in common' => 'so do I / neither do I  ',
            'When I met you' => 'past simple and past continuous',
            'Describing a city' => '',
            'My life story' => 'present perfect and present perfect continuous',
            'Office work' => 'auxiliary verbs',
            'Movie genres' => 'phrases followed by the gerund',
            'Describing things' => 'present simple passive',
            'Rules in the past' => 'modal verbs - past forms',
            'Unschooling' => 'reported speech',
            'Tips for travellers' => 'for-to+infinitive',
            'Online relationships' => '2nd conditional',
            'Future isn\'t far' => 'probability',
            'Under what circumstances would you…' => 'unreal conditions in present and future',
            'Family values' => 'tenses comparison',
            'Myth or reality' => 'reported speech',
            'Design a tour of your country' => 'articles with geographic names',
            'Things are done in an office' => 'simple passive all forms',
            'Parties' => 'phrases followed by the gerund',
            'Crazy laws in America' => 'modal verbs',
            'Australia' => 'giving recommendations',
            'Writing a resume' => 'regular verbs - spelling',
            'Study techniques' => 'reported speech - simultaneous action',
            'reversing roles' => 'passive voice'
        ),
        // Grammar (2)
        2 => array(
            'Reported Speech Statement',
            'So do I /Neither do I',
            '1st conditional',
            'Relative clauses',
            'Ways of expressing future',
            'Simple passive all forms',
            'Modal verbs - past forms',
            'Present perfect vs. Past simple',
            '2nd conditional',
            'Reported Speech Questions (General Q,Special Q)',
            'Past Perfect & Past Simple',
            'Articles with geographic names',
            '3rd conditional',
            'Phrases followed by the infinitive',
            'Modal verbs positive and negative',
            'some, any, no ( body, thing, where ) +, -, ?',
            'Noun-forming suffixes, adjective-forming suffixes',
            'Prepositions of time and place',
            'Used to /Be used to/get used to',
            'Present perfect and present perfect continuous',
            'Tag questions',
            'Active voice vs passive voice (on the examples of simple tense forms )',
            'Past Simple vs Past Continuous',
            'Present perfect all meanings',
            'ing, ed, adjectives',
            'Modal verbs of obligations',
            'Preposition+noun, noun+preposition',
            'Negative prefixes',
            'Phrases followed by the gerund',
            'Adjective+preposition'
        ),
        // Discussion (3)
        3 => array(
            'I am unique because…',
            'Marriage contract',
            'Reading habits',
            'Me in childhood',
            'If I were the president',
            'Corporate culture',
            'Success of famous people',
            'The perfect weekend',
            'The best birthday party',
            'Learning online',
            'Twins in a family',
            'Moral values in modern life',
            'Can we make our own luck?',
            'Skills you need for a job',
            'Superstitions and stereotypes',
            'Super power',
            'Leadership and control',
            'Beauty and Beast',
            'Gender differences',
            'Life on the edge - risky things in our life',
            'To be with Russia or to be with EU',
            'What annoys you the most',
            'Art of speech',
            'Language barriers, mixed marriages',
            'The problem of unemployment',
            'Advertising: pros and cons',
            'Domestic violence, how to fight it',
            'Job of my dream',
            'Start up',
            'Censorship',
            'Mass media',
            'Homeless people/animals',
            'Animal experimentations: pros and cons',
            'Gambling',
            'Boorishness',
            'Zoo: pros and cons',
            'Surrogate motherhood',
            'Ban human cloning',
            'For capital punishment or life inprisonment',
            'Social networks + ciber bullying',
            'Teenagers and TV',
            'Supports the legalisation of drugs',
            'Who should be the breadwinner of the family?',
            'Guns: pros and cons',
            'Big family vs the only child',
            'Should we ban smoking in public places',
            'Bribes',
            'What can reveal your personality',
            'Who is the worst chatterbox: men or women',
            'Would you believe in love marriage',
            'Computer technology and privasy',
            'How not to lose your temper',
            'If you could have a conversation with anyone in history, who would it be?',
            'Dreams- are they a link between real and imaginary worlds?',
            'Is there such a thing called “absolute truth”',
            'When is it ok to say a “white lie?”',
            'Why is love blind? Relationships.',
            'Bilingual education. Pros and cons.',
            'Royalty',
            'Would you like a computer to be your teacher?',
            'Reading - an emerging trend or a dying interest?',
            'Are sports and games as important as studies?',
            'Are children over-influenced by fashion these days?',
            'Breakfast is the most important meal of the day',
            'Studying grammar is more important than practising conversation skills',
            'The pros and cons of having a credit card.',
            'Do we need a global language?',
            'Reading books is better than watching films based on them.',
            'What scares you the most and why?',
            'Is homeschooling effective?',
            'The pros and cons of a female President.',
            'Should we let our children believe in Santa?',
            'To be or not to be a vegetarian',
            'Been good and saying truth',
            'Myths in our life'
        ),
        // Listening (7)
        7 => array(
            'Royal family. Princess Diana.',
            'Risky sport.',
            'Never give up. Failures of famous people.',
            'Sightseeing. Wonders of the world.',
            'Cuisine around the world.',
            'J.R.R. Tolkien. “The Lord of the Rings”.',
            'The Rolling Stones (+ the song)',
            'The UFO. Paranormal activities.',
            'Public speeches. Nelson Mandela, Martin Luther King.',
            'The Iron lady. Margaret Thatcher.',
            'Is Ian Fleming a real James Bond? Life facts.',
            'Sir Alexander Fleming, the person who discovered penicillin.',
            'Sir Isaac Newton.',
            'Fashion and styles. Is fashion worth paying?',
            'Education around the world'
        ),
        // Writting (5)
        5 => array(
            'Invitations',
            'e-mail',
            'Essay',
            'Letter of complain',
            'Review',
            'Summary',
            'Recipes',
            'Resume',
            'Menus',
            'Article',
            'News',
            'Write a Conversation',
            'Write a Story about an Object',
            'Finish the Story',
            'Write a Story about This Picture'
        )
    ), 
    
    // Upper-intermediate 
    '4' => array(
        // Complex (1)
        1 => array(
            'Important events in a person\'s life' => 'tenses comparison',
            'Feelings and emotions' => '"as" in clauses of time and reason',
            'Fairy tales' => 'sequence of tenses',
            'Pets' => 'indirect questions',
            'Generation gap' => '',
            'University' => 'future perfect',
            'Christmas in different countries' => 'simple passive',
            'Job interview' => 'present perfect and present perfect continuous',
            'Claude Monet' => 'past perfect',
            'Color predicts personality' => 'revision',
            'A survival story' => 'past continuous',
            'Propetry boom' => 'gerund and infinitive',
            'Learning languages' => 'word-building',
            'A catchy advert' => 'complex subject with the infinitive construction',
            'Prepare for a holiday' => 'have, get something done',
            'A favourite recipe' => 'participle II as an adjective',
            'Romantic love lasts one year' => 'I wish, if only in present and future',
            'Let\'s have a meeting' => 'complex object with the infinitive',
            'Paul McCartney' => 'present perfect continuous vs. present continuous',
            'Happy and sad' => 'reported speech',
            'Well-known stories' => 'sequence of tenses',
            'Cosmetic surgery' => 'have/get something done',
            'It\'s high time to cut our mother\'s apron string' => 'phrasal verbs',
            'If university ecucation is free' => '1st conditional, 2nd conditional',
            'Origin of christmas traditions' => 'past perfect',
            'Table manners' => 'should +perfect invinitive',
            'Would you like to buy a spouse' => 'participle I perfect',
            'Corporate culture' => 'present perfect and present perfect continuous',
            'Show must go on' => 'participle 1',
            'The literature Nobel prize' => 'simple pasive',
            'Education in the developing countries' => 'gerund',
            'Advertising' => 'complex subject with the infinitive construction',
            'Presents' => 'passive with modal verbs',
            'History of dating' => 'I wish I had done',
            'Secrets of an effective meeting' => 'future perfect',
            'More feelings and emotions' => 'unreal conditions in present and future',
            'Dracula' => 'used to, would',
            'A supermarket trolley' => 'present perfect passive',
            'A proper education' => 'sequence of tenses',
            'A 2-km long wedding dress' => 'participle 2',
            'Genetically modified food' => 'complex subject with different infinitives',
            'Prenuptial agreement - a romance killer?' => 'modal verbs with different infinitives',
            'Small talk in businss' => 'the gerund',
            'If I were in your shoes' => 'mixed conditionals',
            'Traits of character' => '3rd conditional',
            'Favourite literary characters' => 'revision',
            'Weddings in different countries' => 'past perfect vs. past simple',
            'True love' => 'phrasal verbs',
            'Chair a meeting' => 'complex object with the infinitive ',
            'I wish it had been better' => 'I wish, if only in the past',
            'Get stressed - stay young' => 'present perfect vs present perfect continuous',
            'Da Vinci Code' => 'continuous trences',
            'things you\'ll never learn at school' => 'different infinitives with the modal verbs of possibility',
            'Famous world holidays' => 'passive forms',
            'Getting together in the 21st century' => 'past perfect continuous',
            'Tricky questions' => 'should have done',
            'The speckled band' => 'revision',
            'Homework at school and university' => '3rd conditional',
            'Healthy food' => 'participle II as an adjective',
            'The place I work in' => 'I wish in present and future'
        ),
        // Grammar (2)
        2 => array(
            'I wish , If only, it\'s high time.. In present and past',
            'Mixed conditional',
            'Have/get something done',
            'Articles',
            'Continuous tenses in active',
            'Infinitives with modal verbs',
            'Complex subject',
            'Participle I (active)',
            'Indirect Questions',
            'Phrasal verbs (break, come, get, go, hang, keep)',
            'Future Perfect & Future Perfect Continuous',
            'Modal verbs with the perfect infinitive',
            'Gerund & gerundial construction',
            'Articles 2 ( hospital, the hospital, shool, the shool, church, the church )',
            'Verb+adverb+preposition',
            'Complex object',
            'Continuous tenses in passive',
            'Perfect tenses in active',
            'Past perfect continuous & present perfect continuous',
            'Future Simple, Pr.Continuous for future, Pr. Simple for future, going to',
            'Perfect tenses in passive',
            'Reported speech & sequence of tenses',
            'Indefinite, Cont, Perfect, Infinitives (active)',
            'Passive with modal verbs',
            'Phrasal verbs (make, pull, put, stand, take)',
            'Participle I (passive)',
            '0, 1st, 2nd  3d conditional',
            'Participle II',
            'Indefinite, Cont, Perfect, Infinitives (passive)',
            'Phrasal verbs (turn, work, run, look, knock)'
        ),
        // Discussion (3)
        3 => array(
            'I am unique because…',
            'Marriage contract',
            'Reading habits',
            'Me in childhood',
            'If I were the president',
            'Corporate culture',
            'Success of famous people',
            'The perfect weekend',
            'The best birthday party',
            'Learning online',
            'Twins in a family',
            'Moral values in modern life',
            'Can we make our own luck?',
            'Skills you need for a job',
            'Superstitions and stereotypes',
            'Super power',
            'Leadership and control',
            'Beauty and Beast',
            'Gender differences',
            'Life on the edge - risky things in our life',
            'To be with Russia or to be with EU',
            'What annoys you the most',
            'Art of speech',
            'Language barriers, mixed marriages',
            'The problem of unemployment',
            'Advertising: pros and cons',
            'Domestic violence, how to fight it',
            'Job of my dream',
            'Start up',
            'Censorship',
            'Mass media',
            'Homeless people/animals',
            'Animal experimentations: pros and cons',
            'Gambling',
            'Boorishness',
            'Zoo: pros and cons',
            'Surrogate motherhood',
            'Ban human cloning',
            'For capital punishment or life inprisonment',
            'Social networks + ciber bullying',
            'Teenagers and TV',
            'Supports the legalisation of drugs',
            'Who should be the breadwinner of the family?',
            'Guns: pros and cons',
            'Big family vs the only child',
            'Should we ban smoking in public places',
            'Bribes',
            'What can reveal your personality',
            'Who is the worst chatterbox: men or women',
            'Would you believe in love marriage',
            'Computer technology and privasy',
            'How not to lose your temper',
            'If you could have a conversation with anyone in history, who would it be?',
            'Dreams- are they a link between real and imaginary worlds?',
            'Is there such a thing called “absolute truth”',
            'When is it ok to say a “white lie?”',
            'Why is love blind? Relationships.',
            'Bilingual education. Pros and cons.',
            'Royalty',
            'Would you like a computer to be your teacher?',
            'Reading - an emerging trend or a dying interest?',
            'Are sports and games as important as studies?',
            'Are children over-influenced by fashion these days?',
            'Breakfast is the most important meal of the day',
            'Studying grammar is more important than practising conversation skills',
            'The pros and cons of having a credit card.',
            'Do we need a global language?',
            'Reading books is better than watching films based on them.',
            'What scares you the most and why?',
            'Is homeschooling effective?',
            'The pros and cons of a female President.',
            'Should we let our children believe in Santa?',
            'To be or not to be a vegetarian',
            'Been good and saying truth',
            'Myths in our life'
        ),
        // Listening (7)
        7 => array(
            'Royal family. Princess Diana.',
            'Risky sport.',
            'Never give up. Failures of famous people.',
            'Sightseeing. Wonders of the world.',
            'Cuisine around the world.',
            'J.R.R. Tolkien. “The Lord of the Rings”.',
            'The Rolling Stones (+ the song)',
            'The UFO. Paranormal activities.',
            'Public speeches. Nelson Mandela, Martin Luther King.',
            'The Iron lady. Margaret Thatcher.',
            'Is Ian Fleming a real James Bond? Life facts.',
            'Sir Alexander Fleming, the person who discovered penicillin.',
            'Sir Isaac Newton.',
            'Fashion and styles. Is fashion worth paying?',
            'Education around the world'
        ),
        // Writting (5)
        5 => array(
            'Invitations',
            'e-mail',
            'Essay',
            'Letter of complain',
            'Review',
            'Summary',
            'Recipes',
            'Resume',
            'Menus',
            'Article',
            'News',
            'Write a Conversation',
            'Write a Story about an Object',
            'Finish the Story',
            'Write a Story about This Picture'
        )
    ),
    '6' => array(
        1 => array(
            'Meeting people' => 'I, you, I don\'t have',
            'Countries' => 'he, she it + is',
            'Bears are brown' => 'are',
            'Days of the week' => 'simple',
            'Juicy apples' => 'I like',
            'On the table, under the box' => 'on, in, under, behind',
            'Colours around' => 'I want, I like',
            'Simpsons family' => 'possessives',
            'In my bag' => 'I have, I don\'t have',
            'Famous brands' => 'adjectives',
            'Daily routines' => 'common verbs',
            'Feelings' => 'adjectives',
            'How many' => 'how many',
            'How often' => 'How often'
        )
    )
);
    
}


$tt = array();
foreach ($topics as $LevelID => $LevelDATA) {
    $topicInfo = array();
    $topicInfo['levelID'] = $LevelID;
    foreach ($LevelDATA as $LessonTypeID => $topics) {
        $topicInfo['lessontypeID'] = $LessonTypeID;
        foreach ($topics as $name => $grammar) {
            if ($LessonTypeID == 1) {
                // Complex lessons
                $topicInfo['name'] = $name;
                $topicInfo['grammar'] = $grammar;
            } else {
                // Other lessons
                $topicInfo['name'] = $grammar;
                $topicInfo['grammar'] = '';
            }
            $tt[] = $topicInfo;
        }
    }
}

$q = 'INSERT INTO `'.cnf::$db_prefix.'lesson_topics` VALUES';

for ($i = 0, $n = count($tt); $i < $n; $i++) {
    if ($i != 0) {
        $q .= ',';
    }
    $q .= '(0, "' . mysql_real_escape_string($tt[$i]['name']) . '", ' . $tt[$i]['levelID'] . ', ' . $tt[$i]['lessontypeID'] . ', "' . mysql_real_escape_string($tt[$i]['grammar']) . '")';
}

mysql_query($q) or die(mysql_error());

